### ISSUE TITLE
Inverse FFT

### ISSUE THREAD

**Issue by matthewfarstad** [adis300/fft-c#3]
Hello!

Excellent library. I am trying to apply inverse fft. Can I not just run `fft_forward` and `fft_backward` with the same transformer? I've also tried making a new transformer for backward and that didn't work either. Comparing initial data to data after forward/backward should give same information, yes?

**Comment by adis300** [comment]
Yes you can. If you want to get the original input, it's better to use the output from fft_forward as input for fft_backward. Please refer to https://www.netlib.org/fftpack/ this library is a wrapper for this code.
